#
_nox_vhost() {

	local cur prev opts lists_path arg_site
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"
	opts="-c -C -d -D -s -v -u"
	lists_path='/MesDonnees/www/'
	arg_site=''

	case "${prev}" in
		-s)
			#COMPREPLY=( $( cd $lists_path && compgen -d -- ${cur} | grep '^dev.*') )
			COMPREPLY=( $( compgen -d -- "$lists_path") )
			return 0
			;;
		-v)
			for (( i=0; i < ${#COMP_WORDS[@]}-1; i++)); do
				if [[ ${COMP_WORDS[i]} == @(-s) ]]; then
					arg_site="${COMP_WORDS[$(( $i + 1 ))]}"
				fi
			done
			if [ -n "$arg_site" ]; then
				#COMPREPLY=($(cd "$lists_path/$arg_site" && { compgen -d -- ${cur} | grep '[0-9]+' }))
				COMPREPLY=($( compgen -d -- "$lists_path/$arg_site" | grep '^[0-9]'))
			fi
			return 0
			;;
		*)
		;;
	esac

	COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
}
complete -F _nox_vhost nox_vhost
