#Usage:
#	edsh -s <site_web> -v <version> [-d]
#
_www-sync() {

	local cur prev opts lists_path arg_site
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"
	opts="-s -v -h"
	lists_path='/var/www/'
	arg_site=''

	case "${prev}" in
		-s)
			COMPREPLY=( $( cd $lists_path && compgen -d -- ${cur} | grep '^dev.*') )
			return 0
			;;
		-v)
			for (( i=0; i < ${#COMP_WORDS[@]}-1; i++)); do
				if [[ ${COMP_WORDS[i]} == @(-s|--site) ]]; then
					arg_site="${COMP_WORDS[$(( $i + 1 ))]}"
				fi
			done
			if [ -n "$arg_site" ]; then
				COMPREPLY=( $( cd "$lists_path/$arg_site" && compgen -d -- ${cur} | grep '^v.*') )
			fi
			return 0
			;;
		*)
		;;
	esac

	COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
}
complete -F _www-sync www-sync








_add_product() {
	local cur prev opts lists_path arg_site
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"
	opts="-p -u -h"
	lists_path='/var/www/'
	arg_site=''
	case "${prev}" in
		-p)
			COMPREPLY=( $( cd $lists_path && compgen -d -- ${cur}) )
			return 0
			;;
		*)
		;;
	esac

	COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
}
complete -F _add_product add_product.sh




_add_version() {
	local cur prev opts lists_path arg_site
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"
	opts="-p -g -h"
	lists_path='/var/www/'
	arg_site=''

	case "${prev}" in
		-p)
			COMPREPLY=( $( cd $lists_path && compgen -d -- ${cur}) )
			return 0
			;;
		-g)
			for (( i=0; i < ${#COMP_WORDS[@]}-1; i++)); do
				if [[ ${COMP_WORDS[i]} == @(-p|--product) ]]; then
					arg_site="${COMP_WORDS[$(( $i + 1 ))]}"
				fi
			done
			if [ -n "$arg_site" ]; then
				COMPREPLY=( $( cd "$lists_path/$arg_site" && compgen -d -- ${cur} | grep -E '^[0-9\.]+') )
			fi
			return 0
			;;
		*)
		;;
	esac

	COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
}
complete -F _add_version add_version.sh


_set_current() {
	local cur prev opts lists_path arg_site
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"
	opts="-p -g -h"
	lists_path='/var/www/'
	arg_site=''

	case "${prev}" in
		-p)
			COMPREPLY=( $( cd $lists_path && compgen -d -- ${cur}) )
			return 0
			;;
		-g)
			for (( i=0; i < ${#COMP_WORDS[@]}-1; i++)); do
				if [[ ${COMP_WORDS[i]} == @(-p|--product) ]]; then
					arg_site="${COMP_WORDS[$(( $i + 1 ))]}"
				fi
			done
			if [ -n "$arg_site" ]; then
				COMPREPLY=( $( cd "$lists_path/$arg_site" && compgen -d -- ${cur} | grep -E '^[0-9\.]+') )
			fi
			return 0
			;;
		*)
		;;
	esac

	COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
}
complete -F _set_current set_current.sh

_add_vhost() {
	local cur prev opts lists_path arg_site
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"
	opts="-p -u -h"
	lists_path='/var/www/'
	arg_site=''

	case "${prev}" in
		-u)
			COMPREPLY=( $( compgen -u -- ${cur} ) )
			return 0
			;;
		-p)
			COMPREPLY=( $( cd $lists_path && compgen -d -- ${cur}) )
			return 0
			;;
		*)
			;;
	esac

	COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
}
complete -F _add_vhost add_vhost.sh

# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
